-- ============================================================
-- Project : 가치투자 종목 발굴 서비스 (Value Stock Discovery Service)
-- Database: MySQL
-- Source  : doc/db.md
-- Generated by /dbDesign
-- ============================================================

-- ------------------------------------------------------------
-- Table: market_index
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS market_index (
    id            BIGINT       NOT NULL AUTO_INCREMENT,
    base_dt       DATE         NOT NULL,
    kospi_close   DECIMAL(10,2),
    kospi_vs      DECIMAL(10,2),
    kosdaq_close  DECIMAL(10,2),
    kosdaq_vs     DECIMAL(10,2),
    created_at    DATETIME     NOT NULL DEFAULT NOW(),
    updated_at    DATETIME     NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    PRIMARY KEY (id),
    UNIQUE KEY uq_market_index_base_dt (base_dt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- Table: exchange
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS exchange (
    id            BIGINT       NOT NULL AUTO_INCREMENT,
    base_dt       DATE         NOT NULL,
    usd_krw_rate  DECIMAL(10,2),
    usd_krw_vs    DECIMAL(10,2),
    created_at    DATETIME     NOT NULL DEFAULT NOW(),
    updated_at    DATETIME     NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    PRIMARY KEY (id),
    UNIQUE KEY uq_exchange_base_dt (base_dt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- Table: company
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS company (
    stock_code  VARCHAR(6)   NOT NULL,
    corp_code   VARCHAR(8)   NOT NULL,
    corp_name   VARCHAR(100) NOT NULL,
    corp_cls    CHAR(1),
    created_at  DATETIME     NOT NULL DEFAULT NOW(),
    updated_at  DATETIME     NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    PRIMARY KEY (stock_code),
    UNIQUE KEY uq_company_corp_code (corp_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- Table: financial_statement
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS financial_statement (
    id                      BIGINT      NOT NULL AUTO_INCREMENT,
    bsns_year               CHAR(4)     NOT NULL,
    stock_code              VARCHAR(6)  NOT NULL,
    reprt_code              VARCHAR(5)  NOT NULL,
    fs_div                  VARCHAR(5)  NOT NULL,
    period_nm               VARCHAR(50),
    period_dt               VARCHAR(50),
    current_assets          BIGINT,
    non_current_assets      BIGINT,
    total_assets            BIGINT,
    current_liabilities     BIGINT,
    non_current_liabilities BIGINT,
    total_liabilities       BIGINT,
    capital_stock           BIGINT,
    retained_earnings       BIGINT,
    total_equity            BIGINT,
    revenue                 BIGINT,
    operating_income        BIGINT,
    income_before_tax       BIGINT,
    net_income              BIGINT,
    currency                VARCHAR(10),
    PRIMARY KEY (id),
    CONSTRAINT fk_fs_company
        FOREIGN KEY (stock_code) REFERENCES company (stock_code)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- Table: stock_price
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stock_price (
    id            BIGINT        NOT NULL AUTO_INCREMENT,
    bas_dt        DATE          NOT NULL,
    srtn_cd       VARCHAR(6)    NOT NULL,
    isin_cd       VARCHAR(12),
    itms_nm       VARCHAR(100),
    mrkt_ctg      VARCHAR(10),
    clpr          BIGINT,
    vs            BIGINT,
    flt_rt        DECIMAL(10,2),
    mkp           BIGINT,
    hipr          BIGINT,
    lopr          BIGINT,
    trqu          BIGINT,
    tr_prc        BIGINT,
    lstg_st_cnt   BIGINT,
    mrkt_tot_amt  BIGINT,
    created_at    DATETIME      NOT NULL DEFAULT NOW(),
    updated_at    DATETIME      NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    PRIMARY KEY (id),
    CONSTRAINT fk_sp_company
        FOREIGN KEY (srtn_cd) REFERENCES company (stock_code)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- Table: dividend_info
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dividend_info (
    id              BIGINT      NOT NULL AUTO_INCREMENT,
    corp_code       VARCHAR(8)  NOT NULL,
    dividend_kind   VARCHAR(6),
    dividend_amount BIGINT,
    stlm_dt         DATETIME,
    PRIMARY KEY (id),
    UNIQUE KEY uq_dividend_corp_code (corp_code),
    CONSTRAINT fk_div_company
        FOREIGN KEY (corp_code) REFERENCES company (corp_code)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- Table: stock_indicator
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stock_indicator (
    id               BIGINT          NOT NULL AUTO_INCREMENT,
    stock_code       VARCHAR(6)      NOT NULL,
    calc_year        CHAR(4)         NOT NULL,
    bsns_year        CHAR(4),
    reprt_code       VARCHAR(10),
    base_dt          DATE,
    eps              DECIMAL(15,2),
    bps              DECIMAL(15,2),
    per              DECIMAL(10,2),
    pbr              DECIMAL(10,4),
    roe              DECIMAL(10,4),
    operating_margin DECIMAL(10,4),
    debt_ratio       DECIMAL(10,4),
    dividend_yield   DECIMAL(10,4),
    calculated_at    DATETIME,
    created_at       DATETIME        NOT NULL DEFAULT NOW(),
    updated_at       DATETIME        NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    PRIMARY KEY (id),
    UNIQUE KEY uq_indicator_stock_year (stock_code, calc_year),
    CONSTRAINT fk_si_company
        FOREIGN KEY (stock_code) REFERENCES company (stock_code)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- Table: top100
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS top100 (
    id          BIGINT      NOT NULL AUTO_INCREMENT,
    base_dt     DATE        NOT NULL,
    corp_code   VARCHAR(8)  NOT NULL,
    stock_code  VARCHAR(6)  NOT NULL,
    score       INT,
    created_at  DATETIME    NOT NULL DEFAULT NOW(),
    updated_at  DATETIME    NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    PRIMARY KEY (id),
    CONSTRAINT fk_top100_company_stock
        FOREIGN KEY (stock_code) REFERENCES company (stock_code)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_top100_company_corp
        FOREIGN KEY (corp_code) REFERENCES company (corp_code)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- Table: user
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
    id          BIGINT               NOT NULL AUTO_INCREMENT,
    email       VARCHAR(255)         NOT NULL,
    password    VARCHAR(255)         NOT NULL,   -- [암호화 필요: BCrypt]
    nickname    VARCHAR(50)          NOT NULL,
    role        ENUM('USER','ADMIN') NOT NULL DEFAULT 'USER',
    created_at  DATETIME             NOT NULL DEFAULT NOW(),
    updated_at  DATETIME             NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    PRIMARY KEY (id),
    UNIQUE KEY uq_user_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- Table: user_favorite
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_favorite (
    id          BIGINT      NOT NULL AUTO_INCREMENT,
    user_id     BIGINT      NOT NULL,
    stock_code  VARCHAR(6)  NOT NULL,
    created_at  DATETIME    NOT NULL DEFAULT NOW(),
    updated_at  DATETIME    NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    PRIMARY KEY (id),
    UNIQUE KEY uq_favorite_user_stock (user_id, stock_code),
    CONSTRAINT fk_uf_user
        FOREIGN KEY (user_id) REFERENCES `user` (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_uf_company
        FOREIGN KEY (stock_code) REFERENCES company (stock_code)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- Table: investment_journal
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS investment_journal (
    id          BIGINT       NOT NULL AUTO_INCREMENT,
    user_id     BIGINT       NOT NULL,
    title       VARCHAR(200) NOT NULL,
    content     TEXT         NOT NULL,
    created_at  DATETIME     NOT NULL DEFAULT NOW(),
    updated_at  DATETIME     NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    PRIMARY KEY (id),
    CONSTRAINT fk_ij_user
        FOREIGN KEY (user_id) REFERENCES `user` (id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- Table: comment
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS comment (
    id          BIGINT   NOT NULL AUTO_INCREMENT,
    journal_id  BIGINT   NOT NULL,
    user_id     BIGINT   NOT NULL,
    content     TEXT     NOT NULL,
    created_at  DATETIME NOT NULL DEFAULT NOW(),
    updated_at  DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    PRIMARY KEY (id),
    CONSTRAINT fk_comment_journal
        FOREIGN KEY (journal_id) REFERENCES investment_journal (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_comment_user
        FOREIGN KEY (user_id) REFERENCES `user` (id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX idx_company_corp_name   ON company             (corp_name);
CREATE INDEX idx_fs_lookup           ON financial_statement (stock_code, bsns_year, reprt_code);
CREATE INDEX idx_stock_price_lookup  ON stock_price         (srtn_cd, bas_dt);
CREATE INDEX idx_indicator_per       ON stock_indicator     (per);
CREATE INDEX idx_indicator_pbr       ON stock_indicator     (pbr);
CREATE INDEX idx_indicator_roe       ON stock_indicator     (roe);
CREATE INDEX idx_indicator_debt      ON stock_indicator     (debt_ratio);
CREATE INDEX idx_top100_base_dt      ON top100              (base_dt, score);
CREATE INDEX idx_journal_user_id     ON investment_journal  (user_id);
CREATE INDEX idx_comment_journal_id  ON comment             (journal_id);
